insert into question (text) values ('Handelt es sich um eine fiktive Figur?');
insert into question (text) values ('Ist die Figur weiblich?');
insert into question (text) values ('Ist die Figur menschlich?');
insert into question (text) values ('Ist die Figur vor dem Jahr 2000 verstorben?');
insert into question (text) values ('Ist die Figur aus Kino oder Fernsehen bekannt?');
insert into question (text) values ('Ist die Figur für ihre Musik bekannt?');
insert into question (text) values ('Ist die Figur Wissenschaftler?');
insert into question (text) values ('Ist die Figur Politiker?');
insert into question (text) values ('Hat die Figur etwas mit Sport zu tun?');
insert into question (text) values ('Kann die Figur fliegen?');
insert into question (text) values ('Wird die Figur hin und wieder mit einem Apfel in Verbindung gebracht?');
insert into question (text) values ('Wurde die Figur in Europa geboren?');
insert into question (text) values ('Wurde die Figur in den USA geboren?');
insert into question (text) values ('Ist die Figur nach 1950 geboren?');
insert into question (text) values ('Ist die Figur weltweit bekannt?');
insert into question (text) values ('Trägt die Figur eine Waffe?');
insert into question (text) values ('Ist die Figur hauptsächlich durch eine Fernsehserie bekannt?');
insert into question (text) values ('War oder ist die Figur verheiratet?');
insert into question (text) values ('Hat die Figur eine Katze als Haustier?');
insert into question (text) values ('War die Figur bereits im Weltall?');
insert into question (text) values ('War die Figur bereits wegen Drogenproblemen in den Medien?');
insert into question (text) values ('Fängt der Name (Vorname oder Künstlername) mit einem Vokal an?');
insert into question (text) values ('Hat man die Figur oft auf Pferden gesehen?');
--
insert into celebrity (name, description, image_url) values ('Steve Jobs', 'Apple, NeXT and Pixar', null);
insert into celebrity (name, description, image_url) values ('Audrey Hepburn', 'Schauspielerin', null);
insert into celebrity (name, description, image_url) values ('Keanu Reeves', 'Schauspieler', null);
insert into celebrity (name, description, image_url) values ('Donald F. Duck', 'Cholerische Ente', null);
insert into celebrity (name, description, image_url) values ('Albert Einstein', 'Physik-Nobelpreisträger', null);
insert into celebrity (name, description, image_url) values ('R2D2', 'Androide in der Star Wars Saga', null);
insert into celebrity (name, description, image_url) values ('Data', 'Androide in Star Trek - The Next Generation', null);
insert into celebrity (name, description, image_url) values ('Daniel Glattauer', 'Österreichischer Autor und Schriftsteller', null);
insert into celebrity (name, description, image_url) values ('Raymond Radiguet', 'Französischer Schriftsteller (Le Diable au Corps)', null);
insert into celebrity (name, description, image_url) values ('Gottlieb Daimler', 'Deutscher Ingenieur - einer der Väter des Automobils', null);
insert into celebrity (name, description, image_url) values ('Jessica Lowndes', 'Schauspielerin', null);
insert into celebrity (name, description, image_url) values ('Shenae Grimes-Beech', 'Schauspielerin', null);
insert into celebrity (name, description, image_url) values ('Shania Twain', 'Musikerin', null);
insert into celebrity (name, description, image_url) values ('Sherlock Holmes', 'Romanfigur', null);
insert into celebrity (name, description, image_url) values ('James Bond', 'Roman- und Filmfigur', null);
insert into celebrity (name, description, image_url) values ('Sean Connery', 'Schauspieler', null);
insert into celebrity (name, description, image_url) values ('William Shakespeare', 'Schriftsteller', null);
insert into celebrity (name, description, image_url) values ('Alan Turing', 'Pionier der Informatik', null);
insert into celebrity (name, description, image_url) values ('Konrad Zuse', 'Erbauer des ersten Computers', null);
insert into celebrity (name, description, image_url) values ('Charles Babbage', 'Mathematiker, Philosoph, Erfinder der ''Analytical Engine''', null);
insert into celebrity (name, description, image_url) values ('Ada Lovelace', 'Allgemein als erste Programmiererin betrachtet', null);
insert into celebrity (name, description, image_url) values ('Joyce Jonathan', 'Musikerin', null);
insert into celebrity (name, description, image_url) values ('Neil Armstrong', 'Erster Mensch auf dem Mond', null);
